COMFY=ComfyUI
nohup bash -c "modelscope download --model Comfy-Org/z_image split_files/diffusion_models/z_image_bf16.safetensors --local_dir /tmp/dl_z_bf16 && mkdir -p $COMFY/models/diffusion_models && mv /tmp/dl_z_bf16/split_files/diffusion_models/z_image_bf16.safetensors $COMFY/models/diffusion_models/ && rm -rf /tmp/dl_z_bf16" > z_bf16.log 2>&1 &
nohup bash -c "modelscope download --model Comfy-Org/z_image split_files/text_encoders/qwen_3_4b_fp8_mixed.safetensors --local_dir /tmp/dl_z_te_fp8 && mkdir -p $COMFY/models/text_encoders && mv /tmp/dl_z_te_fp8/split_files/text_encoders/qwen_3_4b_fp8_mixed.safetensors $COMFY/models/text_encoders/ && rm -rf /tmp/dl_z_te_fp8" > z_te_fp8.log 2>&1 &
nohup bash -c "modelscope download --model Comfy-Org/z_image split_files/vae/ae.safetensors --local_dir /tmp/dl_z_vae && mkdir -p $COMFY/models/vae && mv /tmp/dl_z_vae/split_files/vae/ae.safetensors $COMFY/models/vae/ && rm -rf /tmp/dl_z_vae" > z_vae.log 2>&1 &
nohup bash -c "modelscope download --model unsloth/Qwen-Image-Edit-2511-GGUF qwen-image-edit-2511-Q4_K_M.gguf --local_dir /tmp/dl_ged_unet && mkdir -p $COMFY/models/unet && mv /tmp/dl_ged_unet/qwen-image-edit-2511-Q4_K_M.gguf $COMFY/models/unet/ && rm -rf /tmp/dl_ged_unet" > ged_unet.log 2>&1 &
nohup bash -c "modelscope download --model unsloth/Qwen2.5-VL-7B-Instruct-GGUF Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf --local_dir /tmp/dl_ged_clip && mkdir -p $COMFY/models/clip && mv /tmp/dl_ged_clip/Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf $COMFY/models/clip/ && rm -rf /tmp/dl_ged_clip" > ged_clip.log 2>&1 &
nohup bash -c "modelscope download --model unsloth/Qwen2.5-VL-7B-Instruct-GGUF mmproj-F16.gguf --local_dir /tmp/dl_ged_mmproj && mkdir -p $COMFY/models/clip && mv /tmp/dl_ged_mmproj/mmproj-F16.gguf $COMFY/models/clip/Qwen2.5-VL-7B-Instruct-mmproj-BF16.gguf && rm -rf /tmp/dl_ged_mmproj" > ged_mmproj.log 2>&1 &
nohup bash -c "modelscope download --model Comfy-Org/Qwen-Image_ComfyUI split_files/vae/qwen_image_vae.safetensors --local_dir /tmp/dl_ed_vae && mkdir -p $COMFY/models/vae && mv /tmp/dl_ed_vae/split_files/vae/qwen_image_vae.safetensors $COMFY/models/vae/ && rm -rf /tmp/dl_ed_vae" > ed_vae.log 2>&1 &
nohup bash -c "modelscope download --model lightx2v/Qwen-Image-Edit-2511-Lightning Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors --local_dir /tmp/dl_ed_lora && mkdir -p $COMFY/models/loras && mv /tmp/dl_ed_lora/Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors $COMFY/models/loras/ && rm -rf /tmp/dl_ed_lora" > ed_lora.log 2>&1 &
nohup bash -c "modelscope download --model fal/Qwen-Image-Edit-2511-Multiple-Angles-LoRA qwen-image-edit-2511-multiple-angles-lora.safetensors --local_dir /tmp/dl_ed_angles && mkdir -p $COMFY/models/loras && mv /tmp/dl_ed_angles/qwen-image-edit-2511-multiple-angles-lora.safetensors $COMFY/models/loras/ && rm -rf /tmp/dl_ed_angles" > ed_angles.log 2>&1 &
nohup bash -c "modelscope download --model Comfy-Org/Wan_2.2_ComfyUI_Repackaged split_files/diffusion_models/wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors --local_dir /tmp/dl_wan_h && mkdir -p $COMFY/models/diffusion_models && mv /tmp/dl_wan_h/split_files/diffusion_models/wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors $COMFY/models/diffusion_models/ && rm -rf /tmp/dl_wan_h" > wan_h.log 2>&1 &
nohup bash -c "modelscope download --model Comfy-Org/Wan_2.2_ComfyUI_Repackaged split_files/diffusion_models/wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors --local_dir /tmp/dl_wan_l && mkdir -p $COMFY/models/diffusion_models && mv /tmp/dl_wan_l/split_files/diffusion_models/wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors $COMFY/models/diffusion_models/ && rm -rf /tmp/dl_wan_l" > wan_l.log 2>&1 &
nohup bash -c "modelscope download --model Comfy-Org/Wan_2.2_ComfyUI_Repackaged split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors --local_dir /tmp/dl_wan_te && mkdir -p $COMFY/models/text_encoders && mv /tmp/dl_wan_te/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors $COMFY/models/text_encoders/ && rm -rf /tmp/dl_wan_te" > wan_te.log 2>&1 &
nohup bash -c "modelscope download --model Comfy-Org/Wan_2.2_ComfyUI_Repackaged split_files/vae/wan_2.1_vae.safetensors --local_dir /tmp/dl_wan_vae && mkdir -p $COMFY/models/vae && mv /tmp/dl_wan_vae/split_files/vae/wan_2.1_vae.safetensors $COMFY/models/vae/ && rm -rf /tmp/dl_wan_vae" > wan_vae.log 2>&1 &
nohup bash -c "modelscope download --model Kijai/WanVideo_comfy Lightx2v/lightx2v_I2V_14B_720p_cfg_step_distill_rank_128_bf16.safetensors --local_dir /tmp/dl_wan_lora720 && mkdir -p $COMFY/models/loras && mv /tmp/dl_wan_lora720/Lightx2v/lightx2v_I2V_14B_720p_cfg_step_distill_rank_128_bf16.safetensors $COMFY/models/loras/ && rm -rf /tmp/dl_wan_lora720" > wan_lora720.log 2>&1 &s